import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import Header from "./components/main/Header";
import Link from "next/link";
import Footer from "./components/main/Footer";

export const metadata: Metadata = {
  title: "paranmanzang",
  description: "Generated by create paran front",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Paranmanzang</title>
        <ThemeModeScript />
      </head>
      <body>
        <Header />
        <main className="my-6 py-6">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
