import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import RecommendBook from "./components/chat/ChatBot/RecommendBook";

export const metadata: Metadata = {
  title: "paranmanzang",
  description: "Generated by create paran front",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Paranmanzang</title>
        <ThemeModeScript />
      </head>
      <body>
        <Header />
        <main className="mb-6 pb-6">{children}</main>
        <RecommendBook />
        <Footer />
      </body>
      {/* Kakao SDK 스크립트 로드 */}
      {/* <Script
            src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.2/kakao.min.js"
            integrity="sha384-TiCUE00h649CAMonG018J2ujOgDKW/kVWlChEuu4jK2vxfAAD0eZxzCKakxg55G4"
            crossOrigin="anonymous"
            strategy="afterInteractive" // 클라이언트 사이드에서만 로드되도록 설정
          />
          */}
    </html>
  );
}
