import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "paranmanzang",
  description: "Generated by create paran front",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <title>Paranmanzang</title>
        <ThemeModeScript />
      </head>
      <body>
        <StoreProvider >
          <Header />
          <main className="mb-6 pb-6">{children}</main>
          <div id="map" style={{ width: "100%", height: "400px" }}></div>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}